Set proguard rules to avoid missing Java classes
When apps that uses libretroshare are compied and proguard is run, Java
  classes coming from libretroshare and that are used only by
  libretroshare C++ code were errouneously stripped by proguard.
  Bundle proper proguard rules in the AAR to avoid runtime errors such
  as
java.lang.ClassNotFoundException: Didn't find class "org.retroshare.service.AssetHelper" on path: DexPathList[[zip file "/data/app/com.example.retroshare_aar